# Generated by Django 6.0.7 on 2026-08-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('linkedIn_url', models.CharField(blank=True, max_length=200, null=True)),
                ('gitHub_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('willing_to_relocate', models.BooleanField()),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_summery', models.TextField(blank=True, max_length=500, null=True)),
                ('preferred_roles', models.CharField(blank=True, max_length=300, null=True)),
                ('preferred_locations', models.CharField(blank=True, max_length=300, null=True)),
                ('total_experience', models.FloatField()),
                ('relevant_experience', models.FloatField()),
                ('languages_know', models.CharField(blank=True, max_length=300, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('current_role', models.CharField(blank=True, max_length=200, null=True)),
                ('current_ctc', models.FloatField(blank=True, null=True)),
                ('expected_ctc', models.FloatField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('LWD_if_resigned', models.DateField(blank=True, null=True)),
                ('immediate_joiner', models.BooleanField()),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('certifications', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
